feat: add DynamoDB script and few methods
RoTorEx/ServerlessApp pull request #1
Opened 2022-07-16 14:55 UTC by RoTorEx

Write main.py script with dynamic conversion of code into class methods.
In DynamoDB realize create and delete methods.

2022-07-16 15:02 UTC, RoTorEx commented
It is interesting to learn how to use primary key indexes correctly in practice: as a number (N) or string (S)?

2022-07-17 09:35 UTC, chalfee requested changes

2022-07-17 09:35 UTC, chalfee commented on Core/base.py
> +        table_name = input("Enter the table name: ")
внутренние классы сервисов не должны обращаться никак к консоли, а параметры должны поступать из вне

2022-07-17 09:35 UTC, chalfee commented on Core/base.py
> +        except Exception as e:
отлавливать Exception далеко не всегда правильно, потому что так ты не контролируешь, что именно обрабатывается
лучше всего отлавливать какие-то конкретные ошибки, например "таблица с таким именем уже существует". потому что в целом такое поведение в принципе ожидаемое
а если ты просто хочешь сделать логирование всех ошибок, то тогда да, можно отловить Exception, залогировать, но после все равно сделать raise

2022-07-17 09:35 UTC, chalfee commented on Core/base.py
> +    def create_table(client, *args, **kwargs):
`*args, **kwargs` не стоит передавать, если ты действительно их не используешь. делать параметры, просто на всякий случай, это не самый хороший тон

2022-07-17 09:35 UTC, chalfee commented on Core/base.py
> +    def create_table(client, *args, **kwargs):
я бы на твоем месте `client` сделал переменной класса через singleton , чтобы не надо было всегда еще один лишний параметр прокидывать

2022-07-18 15:22 UTC, closed without merging